### ISSUE TITLE
Is mpdel-embark ready for testing ?

### ISSUE THREAD

**Issue by dinojr** [mpdel/mpdel-embark#2]
Completion for mpd requests is something i've been looking for and your project is giving me hope. Is mpdel-embark ready for testing, using the [improve-completion](https://gitea.petton.fr/mpdel/libmpdel/src/branch/improve-completion) branch of libmpdel ?

**Comment by DamienCassou** [comment]
Hi @dinojr.

Thank you for your interest in mpdel. I've been using this work for quite some time now and the only missing piece is a bit of motivation to clean and push. Your message gave me this motivation so I will do that.

The `improve-completion` branch has been merged already and I've just released v2.

I now need to cleanup https://github.com/mpdel/mpdel-embark/pull/1 and get it merged. You should be able to use it immediately though.

**Comment by dinojr** [comment]
I've not yet figured out how to use it.
mpdel-embark-list offers to navigate through artist->album->song but embark-act doesn't propose any of the mpdel-embark--commands.

"Search by artist" from mpdel browser tablist buffer doesn't seem to use completion.

**Comment by DamienCassou** [comment]
Hi @dinojr,

I've just merged PR https://github.com/mpdel/mpdel-embark/pull/1 and added a README. Would you mind testing that and opening new issues for the problems you face?

I will close this issue now.

**Comment by dinojr** [comment]
Thanks for the README. With (mpdel-embark-setup) embark-act is now proposing the mpdel core functions from the the mpdel-embark-alist and successfully manipulate the playlist. I get however the following warning message:
`Error in process filter: Quit`

Also "i" is undefined in the MPDel browser buffer.

**Comment by dinojr** [comment]
Also the package is not yet available either through melpa or melpa-stable so the `(use-package)`  mentioned in the README fails but I guess it's just a matter of time.

**Comment by DamienCassou** [comment]
> I get however the following warning message: `Error in process filter: Quit`

can you please report a new issue with steps to reproduce?

> Also "i" is undefined in the MPDel browser buffer.

can you please report a new issue with steps to reproduce?

> Also the package is not yet available either through melpa or melpa-stable

The PR https://github.com/melpa/melpa/pull/8341 is opened.

**Comment by dinojr** [comment]
Everything seems to be fixed in the new version of mpdel-embark.
